groups:
- interval: 30s
  name: agentic_alerts
  rules:
  - alert: HighErrorRate
    annotations:
      description: Error rate is {{ $value }} errors/sec
      summary: High error rate detected
    expr: rate(agentic_errors_total[5m]) > 0.05
    for: 5m
    labels:
      severity: critical
  - alert: SlowReasoningSteps
    annotations:
      description: P95 latency is {{ $value }}s
      summary: Reasoning steps are slow
    expr: histogram_quantile(0.95, rate(agentic_reasoning_duration_seconds_bucket[5m]))
      > 2
    for: 10m
    labels:
      severity: warning
  - alert: LowDecisionConfidence
    annotations:
      description: Average confidence is {{ $value }}
      summary: Decision confidence is low
    expr: avg(agentic_decision_confidence) < 0.7
    for: 15m
    labels:
      severity: warning
