alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093
global:
  evaluation_interval: 15s
  external_labels:
    cluster: agentic-browser-cluster
    environment: production
  scrape_interval: 15s
rule_files:
- rules/*.yml
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: agentic-python
  metrics_path: /metrics
  static_configs:
  - targets:
    - python-agent:8000
- job_name: agentic-golang
  metrics_path: /metrics
  static_configs:
  - targets:
    - golang-agent:8080
- job_name: kubernetes-pods
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - action: keep
    regex: true
    source_labels:
    - __meta_kubernetes_pod_annotation_prometheus_io_scrape
