logs:
  configs:
  - clients:
    - url: http://loki:3100/loki/api/v1/push
    name: default
metrics:
  configs:
  - name: default
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets:
        - localhost:9090
    - job_name: agentic-python
      metrics_path: /metrics
      static_configs:
      - targets:
        - python-agent:8000
    - job_name: agentic-golang
      metrics_path: /metrics
      static_configs:
      - targets:
        - golang-agent:8080
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_prometheus_io_scrape
server:
  http_listen_port: 12345
  log_level: info
traces:
  configs:
  - exporters:
      otlp:
        endpoint: tempo:4317
        tls:
          insecure: true
    name: default
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 512
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
